language: php
sudo: false

php:
  - 5.6
  - 5.5
  - 5.4
  
before_script:
  - composer self-update
  - composer install --prefer-dist
  - mysql -e "CREATE DATABASE IF NOT EXISTS dbtests DEFAULT CHARACTER SET utf8;" -uroot
  
script: phpunit tests
